config/routes.rb
Rails.application.routes.draw do

  root to: 'mvc#home'

  get 'About', to: 'mvc#about'

  get 'Socials', to: 'mvc#social'

  get 'Contact', to: 'mvc#contact'

  get 'ITC', to: 'mvc#itc'

  get 'Work', to: 'mvc#work'

#Google APIs (Maps)
  get 'ask', to: 'maps#ask'

  get 'show', to: 'maps#show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

#Contact Page <Interactions>

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/nasa_api.rb
class NasaApi < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :what_do_you_want_to_tell_me)
    end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def ask
  end

  def show
  	@location = params[:location]
  	@zip = params[:zip]
  	@map = "https://www.google.com/maps/embed/v1/place?key=DEMO_KEY_GOOGLE
    &q=Best+{@location}+In+#{@zip}+NYC"
  end
end

app/controllers/mvc_controller.rb
class MvcController < ApplicationController
  def home
  end

  def about
  end

  def social
  end

  def contact
  end

  def itc
  end

  def work
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/mvc_helper.rb
module MvcHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :what_do_you_want_to_tell_me %>
    <%= form.text_area :what_do_you_want_to_tell_me, id: :contact_what_do_you_want_to_tell_me %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>What do you want to tell me</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.what_do_you_want_to_tell_me %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>What do you want to tell me:</strong>
  <%= @contact.what_do_you_want_to_tell_me %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

	<!-- Navbar Color -->
	<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
	
		<!-- Image and text
		<nav class="navbar navbar-light bg-faded">
			<a class="navbar-brand" href="#">
				<img src="/assets/brand/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
				Bootstrap
			</a>
		</nav>
		-->

		<!-- Navbar Improved -->
		<ul class="nav">
			<li class="nav-item">
				<a href="/">
					<button type="button" class="btn btn-outline-secondary">Home</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/Contact">
					<button type="button" class="btn btn-outline-secondary">Contact</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/About">
					<button type="button" class="btn btn-outline-secondary">About</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/ITC">
					<button type="button" class="btn btn-outline-secondary">ITC</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/Work">
					<button type="button" class="btn btn-outline-secondary">Work</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/Socials">
					<button type="button" class="btn btn-outline-secondary">Social</button>
				</a>
			</li>
			<li class="nav-item">
				<a href="/ask">
					<button type="button" class="btn btn-outline-secondary">Maps</button>
				</a>
			</li>

			<!-- Navbar Colors
			<button type="button" class="btn btn-outline-primary">Home</button>
			<button type="button" class="btn btn-outline-secondary">Secondary</button>
			<button type="button" class="btn btn-outline-success">Success</button>
			<button type="button" class="btn btn-outline-info">Info</button>
			<button type="button" class="btn btn-outline-warning">Warning</button>
			<button type="button" class="btn btn-outline-danger">Danger</button>
			-->
		</ul>

		<!-- Navbar Colors
		<div class="pos-f-t">
			<div class="collapse" id="navbarToggleExternalContent">
				<div class="bg-inverse p-4">
			    	<h4 class="text-white">Collapsed content</h4>
			    	<span class="text-muted">Home</span>
			    	<span class="text-muted">Contact</span>
			    	<span class="text-muted">About</span>
			    	<span class="text-muted">ITC</span>
			    	<span class="text-muted">Work</span>
			    	<span class="text-muted">Social</span>
			    	<span class="text-muted">Maps</span>
		    	</div>
			</div>

			<nav class="navbar navbar-inverse bg-inverse">
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
			    <span class="navbar-toggler-icon"></span>
			    </button>
			</nav>
		</div> -->
	</nav>

	<head>
		<title>Portfolio</title>
		<%= csrf_meta_tags %>

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	</head>

	<body>
    	<%= yield %>
	</body>

</html>

app/views/maps/ask.html.erb
<center>
	<section class='container'>
		<h1> Where are you? </h1>
		<p> A Jay Production App </p>
	</section>
</center>

<center>
<%= form_tag show_path, method: "get", html: { class: "form" } do %>
	<div class="form-group col-sm-6 col-md-offset-3">
		<%= text_field_tag(:location, "", placeholder: "Enter Location", class: "form-control") %>
	</div>
	<div class="form-group col-sm-6 col-md-offset-3">
		<%= text_field_tag(:zip, "", placeholder: "Enter Food of Choice", class: "form-control") %>
	</div>

	<center>
		<div class="form-group text-center">
			<%=submit_tag "Search", class: " gmaps-btn btn btn-outline-info text-align: center;" %>
			<% end %>
		</div>
	</center>
</center>

app/views/maps/show.html.erb
<h1><%= @place %></h1>

<iframe
  width="600"
  height="450"
  frameborder="0" style="border:0"
  src="<%= @map %>" allowfullscreen>
</iframe>

app/views/mvc/about.html.erb
<h1>Mvc#about</h1>
<p>Find me in app/views/mvc/about.html.erb</p>

app/views/mvc/contact.html.erb
<h1>Mvc#contact</h1>
<p>Find me in app/views/mvc/contact.html.erb</p>

app/views/mvc/home.html.erb
<div class="container-fluid">
	<center>
		<h1>Irene's Portfolio</h1>
	</center>
</div>

app/views/mvc/itc.html.erb
<h1>Mvc#itc</h1>
<p>Find me in app/views/mvc/itc.html.erb</p>

app/views/mvc/social.html.erb
<h1>Mvc#social</h1>
<p>Find me in app/views/mvc/social.html.erb</p>

app/views/mvc/work.html.erb
<h1>Mvc#work</h1>
<p>Find me in app/views/mvc/work.html.erb</p>